// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnmgvhxjehxanhzousjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubWd2aHhqZWh4YW5oem91c2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzk2NzMsImV4cCI6MjA2ODkxNTY3M30.-yLMXi2GTXLhYPQrhRfmL4yK7SqgBIsooTw296Dx1hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});